### PR TITLE
Fixed a case where queryInterval() would not correctly match strict subi...

### PR DESCRIPTION
**Pull request by gdhuse**
Thanks for the useful library!  I found a case where queryInterval() would not return intervals that fully enclose the query, and implemented a change that I believe resolves the issue.  

Best regards,
 Greg

### CODE REVIEW

**Comment by mikolalysenko** [comment]
Thanks, checking this out right now!

**Comment by mikolalysenko** [comment]
Hmm...  There was definitely a bug but this PR has some problems.  The biggest one is that it will degenerate to a brute force O(n) linear scan due to an incorrect binary search.  I'll take a look and see if I can get a better implementation working.

**Comment by gdhuse** [comment]
Hello,

I probably misunderstood the structure -- here's my reasoning.  For any node N with midpoint M, the query interval Q=[Q<sub>lo</sub>, Q<sub>hi</sub>] will either:
1. Contain M (Q<sub>lo</sub> <= M <= Q<sub>hi</sub>), which is handled by [L273](https://github.com/gdhuse/interval-tree-1d/blob/6125e70e7ae599b3cbd51327e0ff5d95a0986e3c/interval-tree.js#L273)
2. Be strictly less than M (Q<sub>lo</sub> <= Q<sub>hi</sub> < M)
3. Or be strictly greater than M (M < Q<sub>lo</sub> <= Q<sub>hi</sub>)

For case (2), Q<sub>lo</sub> < M <= I<sub>hi</sub> for all intervals I in N, so we only need to find intervals where I<sub>lo</sub> <= Q<sub>hi</sub>.  This done on [L237](https://github.com/gdhuse/interval-tree-1d/blob/6125e70e7ae599b3cbd51327e0ff5d95a0986e3c/interval-tree.js#L237) by outputting the intervals sorted by I<sub>lo</sub>,  stopping when we find one where I<sub>lo</sub> > Q<sub>hi</sub>.  Case (3) is the reverse.

I actually verified that removing the conditional on [L231](https://github.com/gdhuse/interval-tree-1d/blob/6125e70e7ae599b3cbd51327e0ff5d95a0986e3c/interval-tree.js#L231) doesn't change the test output (though it's possible some condition is not covered by the test).

Best regards,
 Greg

**Comment by mikolalysenko** [comment]
Ah, I see.  Then the binary search wouldn't be necessary in the first place, which is a bit confusing.  Anyway, I added a few more tests and patched things up a bit.  1.0.2 should work now

**Comment by gdhuse** [comment]
Ah yes, I see what you mean.  I cleaned that up and submitted a new pull request.  Great new test, by the way.

**Pull request closed without merging**
